version: '3.9'

services:
  database_soujunior:
    image: postgres
    container_name: vagas-api-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: linkedin-backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      database_soujunior:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
